version: '3'
services:
  web:
    image: nginx
    links:
      - react
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    volumes:
      - ./docker/nginx/conf.d/site-demo.dev.conf:/etc/nginx/conf.d/site.template:ro
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
  react:
    image: node:latest
    environment:
      - NODE_PATH=${NODE_PATH}
      - NODE_ENV=dev
      - NPM_CONFIG_LOGLEVEL=warn
    working_dir: /home/app
    volumes:
      - ./src:/home/app/src
      - ./public:/home/app/public
      - ./package.json:/home/app/package.json
    command: bash -c "yarn install && yarn start"
